version: "3"
services:
  ts:
    image: timescale/timescaledb:latest-pg12
    environment:
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: zlab
    ports:
      - 35433:5432
