{
 "title": "postgres",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Running Hours",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(reading_time,$__interval),\n  m.name AS metric,\n  avg(value) AS \"value\"\nFROM readings\njoin metrics as m using (metric_id)\nWHERE\n  $__timeFilter(reading_time)\n  and (m.name = 'running_hours')\nGROUP BY time, metric\nORDER BY time, metric"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "table",
   "gridPos": { "h": 27, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT metric_id::integer, name from metrics\norder by metric_id"
    }
   ]
  },
  {
   "title": "Engine",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(reading_time,$__interval),\n  m.name AS metric,\n  avg(value) AS \"value\"\nFROM readings\njoin metrics as m using (metric_id)\nWHERE\n  $__timeFilter(reading_time)\n  and (m.name = 'engine_temperature' or m.name = 'engine_load')\nGROUP BY time, metric\nORDER BY time, metric"
    }
   ]
  },
  {
   "title": "Oil Pressure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(reading_time,$__interval),\n  m.name AS metric,\n  avg(value) AS \"value\"\nFROM readings\njoin metrics as m using (metric_id)\nWHERE\n  $__timeFilter(reading_time)\n  and (m.name = 'oil_presssure' or m.name = 'oil_temperature')\nGROUP BY time, metric\nORDER BY time, metric"
    }
   ]
  }
 ]
}